version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::577638377042:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-1DBYq6w3JHrG"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::577638377042:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-Xlm5roRrXylg"
cloudformation_execution_role = "arn:aws:iam::577638377042:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-wS7nB6eBinnu"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-xtcgyactv7vd"
image_repository = ""
region = "eu-north-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::577638377042:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-rmLOlYuAiO7N"
cloudformation_execution_role = "arn:aws:iam::577638377042:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-WmJz760B2m6s"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-uio9mg5tsnnt"
image_repository = ""
region = "eu-north-1"
